a=int(input("Enter the 1st number : "))
b=int (input("Enter the 2'nd number : "))
print ("The sum is ",a+b)
print ("The substraction is ",a-b)
print ("The multipliaction is ",a*b)
print ("The division is ",a/b)
print ("The modulo is ",a%b)