file = open ("Basic.txt",'a')
file1  = open("Basic2.txt",'w')
file.write  ("My 1st python inbuilt file ")
file.write ("Hope y'all like this ")
file.write("This feels really good")
file1.write ("Module is working !!")
file1.read()
file1.close()
file.close()

